#!/usr/bin/env python3
"""Generate test_vectors.h from shared-protocols/test-vectors/*.json.

Run after regenerating the shared vectors:

    python3 ../../shared-protocols/tools/gen_test_vectors.py
    python3 test/host/sync_vectors.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SHARED = os.path.normpath(os.path.join(HERE, "..", "..", "..", "shared-protocols"))
VEC = os.path.join(SHARED, "test-vectors")
OUT = os.path.join(HERE, "test_vectors.h")

hs = json.load(open(os.path.join(VEC, "handshake.json"), encoding="utf-8"))
pr = json.load(open(os.path.join(VEC, "pairing.json"), encoding="utf-8"))

lines = [
    "/**",
    " * @file test_vectors.h",
    " * @brief Golden values from the shared-protocols/test-vectors directory.",
    " *",
    " * GENERATED by test/host/sync_vectors.py - do not edit by hand.",
    " */",
    "#pragma once",
    "",
    "/* ---------------------------------------------------- handshake.json */",
]


def define(name, value):
    lines.append(f'#define {name} "{value}"')


def define_int(name, value):
    lines.append(f"#define {name} {value}")


for k, v in hs["inputs"].items():
    define("TV_" + k.upper(), v)
for k, v in hs["subkeys"].items():
    define("TV_" + k.upper(), v)
for k, v in hs["handshake"].items():
    define("TV_" + k.upper(), v)

h = hs["hkdf"][0]
define("TV_HKDF_IKM", h["ikm"])
define("TV_HKDF_SALT", h["salt"])
define("TV_HKDF_INFO", h["info"])
define_int("TV_HKDF_LEN", h["length"])
define("TV_HKDF_OKM", h["okm"])

define_int("TV_PSEUDONYM_COUNT", len(hs["pseudonyms"]))
epochs = ", ".join(f'{p["epoch"]}ULL' for p in hs["pseudonyms"])
values = ", ".join(f'"{p["pseudonym"]}"' for p in hs["pseudonyms"])
define_int("TV_PSEUDONYM_EPOCHS", "{ " + epochs + " }")
define_int("TV_PSEUDONYM_VALUES", "{ " + values + " }")

for k, v in hs["frames"].items():
    define("TV_FRAME_" + k.upper(), v["encoded"])
define_int("TV_UNLOCK_COUNTER", hs["frames"]["unlock_event"]["counter"])
define_int("TV_UNLOCK_RESULT", hs["frames"]["unlock_event"]["result"])
define("TV_UNLOCK_TAG", hs["frames"]["unlock_event"]["tag"])

adv = hs["advertisement"]
define("TV_ADV_BYTES", adv["bytes"])
define_int("TV_ADV_FLAGS", adv["flags"])
define_int("TV_ADV_BATTERY", adv["battery_pct"])
define_int("TV_ADV_EPOCH", f'{adv["epoch"]}ULL')

lines += ["", "/* ------------------------------------------------------ pairing.json */"]
define("TV_PAIR_LOCK_ID", pr["inputs"]["lock_id"])
define("TV_PAIR_USER_ID", pr["inputs"]["user_id"])
define("TV_PAIR_PRIV_P", pr["inputs"]["private_phone"])
define("TV_PAIR_PRIV_L", pr["inputs"]["private_lock"])
define("TV_PAIR_NONCE_P", pr["inputs"]["nonce_p"])
define("TV_PAIR_NONCE_L", pr["inputs"]["nonce_l"])
define("TV_PAIR_CODE", pr["inputs"]["pairing_code"])
define("TV_PAIR_PUB_P", pr["x25519"]["public_phone"])
define("TV_PAIR_PUB_L", pr["x25519"]["public_lock"])
define("TV_PAIR_SHARED", pr["x25519"]["shared"])
define("TV_PAIR_TRANSCRIPT", pr["transcript"])
define("TV_PAIR_LTK", pr["ltk"])
define("TV_PAIR_CONFIRM_L", pr["confirm_l"])
define("TV_PAIR_CONFIRM_P", pr["confirm_p"])
define("TV_PAIR_WRONG_CODE_LTK", pr["wrong_code_ltk"])
for k, v in pr["frames"].items():
    define("TV_FRAME_" + k.upper(), v)

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")
print("wrote", OUT)
