#!/usr/bin/env python3
"""Regenerate ../test-vectors/*.json from the reference implementation.

    python3 tools/gen_test_vectors.py

The vectors are consumed by:
  * esp32-firmware/components/smartkey_proto/test/  (Unity, host build)
  * android-app/app/src/test/java/.../protocol/     (JUnit)

Everything is deterministic: all "random" material is fixed below so the files only
change when the protocol itself changes.
"""

from __future__ import annotations

import json
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import skp_crypto as skp  # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "test-vectors")

H = bytes.fromhex


def hx(b: bytes) -> str:
    return b.hex()


# ------------------------------------------------------------------ fixtures

LOCK_ID = H("0102030405060708090a0b0c0d0e0f10")
USER_ID = H("1112131415161718191a1b1c1d1e1f20")
LTK = H("2122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40")
NONCE_L = H("a0a1a2a3a4a5a6a7a8a9aaabacadaeaf")
NONCE_P = H("b0b1b2b3b4b5b6b7b8b9babbbcbdbebf")

PRIV_P = H("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
PRIV_L = H("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")
PAIR_NONCE_P = H("c0c1c2c3c4c5c6c7c8c9cacbcccdcecf")
PAIR_NONCE_L = H("d0d1d2d3d4d5d6d7d8d9dadbdcdddedf")
PAIRING_CODE = "31415926"


def frame(ftype: int, payload: bytes) -> str:
    return hx(bytes([skp.VERSION, ftype]) + struct.pack("<H", len(payload)) + payload)


# ------------------------------------------------------------------ handshake

def build_handshake() -> dict:
    sub = skp.derive_subkeys(LTK, LOCK_ID, USER_ID)
    k_auth, k_beacon = sub["k_auth"], sub["k_beacon"]

    transcript = skp.auth_transcript(LOCK_ID, USER_ID, NONCE_L, NONCE_P)
    tag_p = skp.tag_phone(k_auth, transcript)
    tag_l = skp.tag_lock(k_auth, transcript)
    sid = skp.session_id(k_auth, transcript)
    k_sess = skp.session_key(k_auth, LOCK_ID, USER_ID, NONCE_L, NONCE_P)

    hello_payload = LOCK_ID + NONCE_L + bytes([0x03, 0x00])
    auth_payload = USER_ID + NONCE_P + tag_p
    session_payload = tag_l + sid + bytes([0x01, 0x0A])

    counter, result = 1, 0
    utag = skp.unlock_tag(k_sess, sid, counter, result)
    unlock_payload = sid + struct.pack("<I", counter) + bytes([result, 0x00]) + utag

    epochs = [0, 1, 112233445, 1758412800 // skp.BEACON_EPOCH_SECONDS]
    adv = (struct.pack("<H", 0xFFFF) + bytes([0x4B, skp.VERSION, 0x03])
           + skp.pseudonym(k_beacon, epochs[3]) + bytes([87]))

    return {
        "$comment": "Generated by tools/gen_test_vectors.py - do not edit by hand.",
        "protocol": "SKP1",
        "version": skp.VERSION,
        "inputs": {
            "lock_id": hx(LOCK_ID),
            "user_id": hx(USER_ID),
            "ltk": hx(LTK),
            "nonce_l": hx(NONCE_L),
            "nonce_p": hx(NONCE_P),
        },
        "subkeys": {"k_beacon": hx(k_beacon), "k_auth": hx(k_auth)},
        "hkdf": [{
            "name": "rfc5869-test-case-1",
            "ikm": hx(b"\x0b" * 22),
            "salt": hx(H("000102030405060708090a0b0c")),
            "info": hx(H("f0f1f2f3f4f5f6f7f8f9")),
            "length": 42,
            "okm": hx(skp.hkdf_sha256(b"\x0b" * 22, H("000102030405060708090a0b0c"),
                                      H("f0f1f2f3f4f5f6f7f8f9"), 42)),
        }],
        "pseudonyms": [
            {"epoch": e, "pseudonym": hx(skp.pseudonym(k_beacon, e))} for e in epochs
        ],
        "handshake": {
            "transcript": hx(transcript),
            "tag_p": hx(tag_p),
            "tag_l": hx(tag_l),
            "session_id": hx(sid),
            "k_sess": hx(k_sess),
        },
        "frames": {
            "hello": {"type": 1, "payload": hx(hello_payload),
                      "encoded": frame(1, hello_payload)},
            "auth": {"type": 2, "payload": hx(auth_payload),
                     "encoded": frame(2, auth_payload)},
            "session_ok": {"type": 3, "payload": hx(session_payload),
                           "encoded": frame(3, session_payload)},
            "unlock_event": {"type": 4, "payload": hx(unlock_payload),
                             "encoded": frame(4, unlock_payload),
                             "counter": counter, "result": result, "tag": hx(utag)},
            "presence_ping": {"type": 6, "payload": "", "encoded": frame(6, b"")},
            "error_auth_failed": {"type": 127, "payload": "0400",
                                  "encoded": frame(127, H("0400"))},
        },
        "advertisement": {
            "$comment": "manufacturer specific data payload, company id included",
            "company_id": 65535, "flags": 3, "battery_pct": 87,
            "epoch": epochs[3], "bytes": hx(adv),
        },
    }


# ------------------------------------------------------------------ pairing

def build_pairing() -> dict:
    pub_p = skp.x25519_public(PRIV_P)
    pub_l = skp.x25519_public(PRIV_L)
    z_phone = skp.x25519(PRIV_P, pub_l)
    z_lock = skp.x25519(PRIV_L, pub_p)
    assert z_phone == z_lock, "ECDH mismatch"

    transcript = skp.pair_transcript(LOCK_ID, USER_ID, pub_p, pub_l,
                                     PAIR_NONCE_P, PAIR_NONCE_L)
    ltk = skp.pair_ltk(z_phone, PAIR_NONCE_P, PAIR_NONCE_L, transcript, PAIRING_CODE)
    confirm_l = skp.pair_confirm_lock(ltk, transcript)
    confirm_p = skp.pair_confirm_phone(ltk, transcript)
    wrong = skp.pair_ltk(z_phone, PAIR_NONCE_P, PAIR_NONCE_L, transcript, "00000000")

    return {
        "$comment": "Generated by tools/gen_test_vectors.py - do not edit by hand.",
        "protocol": "SKP1",
        "version": skp.VERSION,
        "inputs": {
            "lock_id": hx(LOCK_ID),
            "user_id": hx(USER_ID),
            "private_phone": hx(PRIV_P),
            "private_lock": hx(PRIV_L),
            "nonce_p": hx(PAIR_NONCE_P),
            "nonce_l": hx(PAIR_NONCE_L),
            "pairing_code": PAIRING_CODE,
        },
        "x25519": {"public_phone": hx(pub_p), "public_lock": hx(pub_l),
                   "shared": hx(z_phone)},
        "transcript": hx(transcript),
        "ltk": hx(ltk),
        "confirm_l": hx(confirm_l),
        "confirm_p": hx(confirm_p),
        "wrong_code_ltk": hx(wrong),
        "derived_subkeys": {k: hx(v) for k, v
                            in skp.derive_subkeys(ltk, LOCK_ID, USER_ID).items()},
        "frames": {
            "pair_start": frame(0x10, USER_ID + pub_p + PAIR_NONCE_P),
            "pair_response": frame(0x11, LOCK_ID + pub_l + PAIR_NONCE_L + confirm_l),
            "pair_confirm": frame(0x12, confirm_p),
            "pair_result_ok": frame(0x13, bytes([0, 0, 0, 0])),
        },
    }


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, data in (("handshake", build_handshake()), ("pairing", build_pairing())):
        path = os.path.normpath(os.path.join(OUT_DIR, name + ".json"))
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(data, fh, indent=2, sort_keys=False)
            fh.write("\n")
        print("wrote", path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
